//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChungTu()
        {
            this.HHTrongKhoes = new HashSet<HHTrongKho>();
            this.HHXKs = new HashSet<HHXK>();
        }
    
        public System.Guid ChungTu1 { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Deleted_Date { get; set; }
        public Nullable<int> Deleted_By { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public Nullable<int> Update_by { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> DVX { get; set; }
        public Nullable<int> NCC { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HHTrongKho> HHTrongKhoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HHXK> HHXKs { get; set; }
        public virtual User User { get; set; }
    }
}
