using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using System.Runtime.Remoting.Contexts;
using DevExpress.Utils.Extensions;

namespace qlkh
{
    public partial class DanhMucHangHoa : DevExpress.XtraEditors.XtraForm
    {
        qlkh.QLKHEntities dbContext = new qlkh.QLKHEntities();
        public DanhMucHangHoa()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //var q = (from a in dbContext.HangHoas.Local where a.NhaCungCap==1 select a);
            //var list = new BindingList<HangHoa>(q.ToList());
            
            dbContext.HangHoas.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                hangHoasBindingSource.DataSource = 
                dbContext.HangHoas.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        QLKHEntities q = new QLKHEntities();
        private void DanhMucHangHoa_Load(object sender, EventArgs e)
        {
            repositoryItemLookUpEdit1.DataSource = q.DonViTinhs.ToList();
            repositoryItemLookUpEdit1.ValueMember= "MaDVT";
            repositoryItemLookUpEdit1.DisplayMember= "TenDVT";
            colDonViTinh.ColumnEdit = repositoryItemLookUpEdit1;

            repositoryItemLookUpEdit2.DataSource = q.NhaCungCaps.ToList();
            repositoryItemLookUpEdit2.ValueMember = "MaNCC";
            repositoryItemLookUpEdit2.DisplayMember = "TenNCC";
            colNhaCungCap.ColumnEdit = repositoryItemLookUpEdit2;

            repositoryItemLookUpEdit3.DataSource = q.QuocGias.ToList();
            repositoryItemLookUpEdit3.ValueMember = "MaQG";
            repositoryItemLookUpEdit3.DisplayMember = "TenQG";
            //C.ColumnEdit = repositoryItemLookUpEdit3;
            //lọc
            //gridView1.ActiveFilterString = "[NhaCungCap] = 1";
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            dbContext.SaveChanges();
        }
    }
}