//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkh
{
    using System;
    using System.Collections.Generic;
    
    public partial class HHTrongKho
    {
        public string MaHH { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<System.Guid> ChungTu { get; set; }
        public int Id { get; set; }
        public Nullable<double> GiaMua { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> SLBan { get; set; }
    
        public virtual ChungTu ChungTu1 { get; set; }
        public virtual HangHoa HangHoa { get; set; }
        public virtual Kho Kho { get; set; }
    }
}
