//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlkh
{
    using System;
    using System.Collections.Generic;
    
    public partial class HHXK
    {
        public Nullable<System.Guid> ChungTu { get; set; }
        public Nullable<int> idhhtk { get; set; }
        public int id { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> SLban { get; set; }
    
        public virtual ChungTu ChungTu1 { get; set; }
        public virtual HHTrongKho HHTrongKho { get; set; }
    }
}
